# Generated by Django 5.0.6 on 2024-07-20 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_alter_reportcard_date_of_report_card_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 7, 20, 21, 57, 52, 973873, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
