# Generated by Django 5.0.6 on 2024-07-01 18:26

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
